cache:
  cacheFormat: universal
  cacheLocation: node_modules/.cache/cspell/.cspell.cache
  cacheStrategy: metadata
  useCache: true
dictionaries:
  - python-common
import:
  - '@kurone-kito/cspell-config'
version: '0.2'
words:
  - libatk
  - libx
  - libxcomposite
  - libxdamage
  - libxrandr
  - libgbm
  - libasound
  - libatspi
  - libxshmfence
  - libxkbcommon
  - libpangocairo
  - npms
  - solidjs
  - vinxi
  - xsea
